### ISSUE TITLE
nvim-ts-rainbow Break in the first parenthesis

### ISSUE THREAD

**Issue by CleoMenezesJr** [navarasu/onedark.nvim#104]
How's it should look like:
![image](https://user-images.githubusercontent.com/54215258/188255667-ee84b8f4-b625-4eda-96bf-619042a6c894.png)

How's it looks like:
![image](https://user-images.githubusercontent.com/54215258/188255708-090c7559-3623-4d52-af45-ab9e5d45ffd1.png)

**Comment by xeluxee** [comment]
Cannot reproduce
Please share the output of `:hi rainbowcol1`

**Comment by abheetChaudhary** [comment]
> How's it should look like: ![image](https://user-images.githubusercontent.com/54215258/188255667-ee84b8f4-b625-4eda-96bf-619042a6c894.png)
> 
> How's it looks like: ![image](https://user-images.githubusercontent.com/54215258/188255708-090c7559-3623-4d52-af45-ab9e5d45ffd1.png)

Happening with me also. The first parenthesis is blending in and disappearing because of the cursor color.
For now, I'm manually setting it to white by running `:hi rainbowcol1 guifg=#eeeeee`. Saw this method on: [https://github.com/p00f/nvim-ts-rainbow#colours](url)
Current behavior: 
![Screenshot_20221021_122201](https://user-images.githubusercontent.com/81126136/197131736-543546bb-f62f-4867-98ff-19615ddcb36c.png)

**Comment by xeluxee** [comment]
What terminal are you using?

> The first parenthesis is blending in and disappearing because of the cursor color.

You can customize cursor color by editing `Cursor` highlight group

> For now, I'm manually setting it to white by running `:hi rainbowcol1 guifg=#eeeeee`.

Instead of manually setting that highlight group you can [customize highlight groups within `setup()` function](https://github.com/navarasu/onedark.nvim#customization)

Anyway your issue could be related to `MatchParen` highlight group not playing well with cursor color.
Try `:hi MatchParen guibg=#37383d guifg=none`

**Comment by abheetChaudhary** [comment]
(I observed this under `style = "deep"`)
I think I have an idea about what the problem is. Under current defaults, to highlight the character under cursor the cursor block becomes the same color as the character and the character becomes some dark shade of blue-grey. All goes well with this setting until ts-rainbow comes in. 

With ts-rainbow this setting changes a little bit when the character under cursor is a parenthesis. Now whenever that happens the cursor block still becomes the same color as the character but now the character takes a specific shade of blue-grey(`#455574`).  By coincidence the same hex value is defined for color "Grey" in [https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua](https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua#L86). By default this same color is set to be used by ts-rainbow plugin for the first-level-parenthesis: [https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/highlights.lua](https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/highlights.lua#L476)

Because of all this now whenever the cursor is on the first-level-parenthesis it first adopts the same color as the parenthesis(`#455574`) then because of some setting the color of the parenthesis is changed to `#455574`(the parenthesis was already this color from the start) and so both the character and cursor are same color now.

This is what I'm trying to say: [first and second level parenthesis.webm](https://user-images.githubusercontent.com/81126136/197323491-c9c7d44a-c500-4566-b550-7117f2dac3d3.webm)
Notice here that when the cursor is on second-level-parenthesis then the character's color changes to `#455574` which is the default color of first-level-parenthesis

To fix this I changed the default color of first-level-parenthesis:
`highlights = {
    rainbowcol1 = {fg = '#eeeeee'},
}`
This is how it works now:
![Screenshot_20221022_115653](https://user-images.githubusercontent.com/81126136/197323980-5c1d3dcb-261e-4266-a05d-520c0931fe29.png)

**Comment by xeluxee** [comment]
This happens because both `MatchParen` background and `rainbowcol1` foreground are grey
https://github.com/navarasu/onedark.nvim/blob/7aeca4713a922139b5e14c037b5faf34dc41c8d2/lua/onedark/highlights.lua#L64
https://github.com/navarasu/onedark.nvim/blob/7aeca4713a922139b5e14c037b5faf34dc41c8d2/lua/onedark/highlights.lua#L477
