### ISSUE TITLE
Bug: Missing GitSign background

### ISSUE THREAD

**Issue by captainko** [navarasu/onedark.nvim#55]
I think we are missing background-color.
I could create PR for this but I don't know how to do it properly.

![image](https://user-images.githubusercontent.com/32269291/149042447-070d5cae-142b-4cee-8d2d-51a0a86b8e6f.png)

**Comment by xeluxee** [comment]
@captainko can you share your onedark setup?

**Comment by captainko** [comment]
> @captainko can you share your onedark setup?
 I use the default config.

> Are you experiencing the same issue with LSP diagnostics signs, such as error and warning signs?

Yeah, all of them are missing the background.

**Comment by captainko** [comment]
Ok I see I'm doing it wrong. I have to set the transparent in the setup method.

**Comment by xeluxee** [comment]
@captainko take a look at how to [customize colors and highlights](https://github.com/navarasu/onedark.nvim#customization), so you don't have to use `nvim_exec`

Also please notice that instead of `hi! DiagnosticVirtualTextError guibg=none` you can disable diagnostics virtual text background with
``` lua
require('onedark').setup {
    diagnostics = {
        background = false,    -- background color for virtual text
    },
}
```

For futher customization give a look at [configuration](https://github.com/navarasu/onedark.nvim#default-configuration)
