### ISSUE TITLE
Terminal Color

### ISSUE THREAD

**Issue by dstadelm** [navarasu/onedark.nvim#71]
Hi I'm using ubuntu terminal and zsh. zsh provides suggestions when changing paths or entering commands based on the history. These are barely readable in the neovim terminal 
I've changed the color for terminal_color_8 from black to grey in terminal.lua
    vim.g.terminal_color_8 = c.grey
Now the terminal in neovim behaves the same as the native terminal.

I'm unsure if this is a change to be done generally or if I shall do it locally in my config.

**_Showcase_**

**terminal_color_8 = c.black**
![onedark_terminal_8_black](https://user-images.githubusercontent.com/3010527/160133006-4e495620-09c2-44ce-9d31-b2a00faff4c4.png)
**terminal_color_8 = c.grey**
![original_behaviour_and_terminal_8_grey](https://user-images.githubusercontent.com/3010527/160133029-36c38c97-b24e-4c14-b3f8-383293b0dff2.png)

**Comment by matthewgrossman** [comment]
Also having this issue; I think `terminal_color_8` and `terminal_color_0` should be swapped. At least based on a couple random plugins I had before adopting this scheme, it seems they all think `0` is `black` and `8` is grey:

With the existing setup:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/2601844/174469802-8bdf3604-4c82-4b97-8a07-853fadbabad3.png">
In this, you can see that the font for my terminal prompt `~/dotfiles | master` has hard to read foreground, because the grey doesn't contrast well. Also (similar to OP), the zsh autocomplete shows text in black, which contrats poorly with the background color.

Both of those issues are fixed after swapping `0` and `8`:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/2601844/174469815-17d65a79-9243-4751-9473-90ac7636469a.png">

I'll put up a PR to swap the colors in the repo shortly. We can discuss if you don't think we want to change this for existing customers (maybe make this customizable somehow? Or just docs on how to change this after-the-setup?)

**Comment by matthewgrossman** [comment]
thanks for the quick merge! closed by https://github.com/navarasu/onedark.nvim/pull/83
